public with sharing class PropertyData {
    public PropertyData() {
System.debug('In Property date Constructor');

    }
    public static void display(string name)
{
System.debug('Name : '+name)
}
public void primeNumber(integer prime)
{
    integer count =0;
    for(integer i=2; i<primeNum; i++)
{
    if(Math.Mod(primeNum,i)==0)
    {
        count++;
        break;
    }
    {
      if(i==primeNum)

    }
    {
        system.debug('Number is prime');

    }
    else
    {
        system.debug('Number is not prime');
    }
}
}


